### ISSUE TITLE
Error when initdb

### ISSUE THREAD

**Issue by smallyin** [sealtalk/sealtalk-server#1]
Hello, I'm a developer interested you project, but when I tried to deploy on my localhost, I got this error infomation:
```
~$:/var/www/html/talkserver$ npm run initdb
> sealtalk-server@1.0.0 initdb /var/www/html/talkserver
> coffee sync.coffee
/var/www/html/talkserver/src/db.coffee:81
      return co(function*() {
                        ^
SyntaxError: Unexpected token *
  at exports.runInThisContext (vm.js:73:16)
  at Module._compile (module.js:443:25)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/var/www/html/talkserver/sync.coffee:1:15)
  at Object.<anonymous> (/var/www/html/talkserver/sync.coffee:1:1)
  at Module._compile (module.js:460:26)
npm ERR! Linux 3.13.0-67-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "initdb"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! sealtalk-server@1.0.0 initdb: `coffee sync.coffee`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sealtalk-server@1.0.0 initdb script 'coffee sync.coffee'.
npm ERR! This is most likely a problem with the sealtalk-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee sync.coffee
npm ERR! You can get their info via:
npm ERR!     npm owner ls sealtalk-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/talkserver/npm-debug.log
```

**I am not very familiar with coffee script, and get stuck here, I'd appreciate if any help of yours, thanks so much.

**Comment by smallyin** [comment]
And my env is: 

```
~$:/var/www/html/talkserver$ npm --version
2.11.3
~$:/var/www/html/talkserver$ coffee --version
CoffeeScript version 1.10.0
~$/var/www/html/talkserver$ node --version
v0.12.7
~$:/var/www/html/talkserver$ uname -a
Linux yin-ubuntu 3.13.0-67-generic #110-Ubuntu SMP Fri Oct 23 13:24:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by arielyang** [comment]
function* is a generator function and it's not be supported by node v0.12 by default. Try "coffee --nodejs --harmony sync.coffee" instead.
