### ISSUE TITLE
N3D怎么获得，为何初始化的时候就编译不过去

### ISSUE THREAD

**Issue by yuanqi1943** [sealtalk/sealtalk-server#13]
Error: The key is error.
    at new N3D (F:\devdir\www\rongyunServer\src\util\n3d.js:26:15)
    at F:\devdir\www\rongyunServer\src\util\util.js:20:17
    at Object.<anonymous> (F:\devdir\www\rongyunServer\src\util\util.js:171:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\devdir\www\rongyunServer\src\db.js:11:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,

**Comment by yuhongda0315** [comment]
请看下 [src/conf.js](https://github.com/sealtalk/sealtalk-server/blob/master/src/conf.js) 中 N3D_KEY 是否有配置？
使用前请参看 conf.js 说明逐项配置
