### ISSUE TITLE
Error when initdb

### ISSUE THREAD

**Issue by alexanderhsiang** [sealtalk/sealtalk-server#2]
#1 Error when initdb on CentOS 7

```
[rongcloud@test1]$ npm run initdb

> sealtalk-server@1.0.0 initdb /home/rongcloud/sealtalk-server
> coffee --nodejs --harmony sync.coffee

(node:24124) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
SyntaxError: In /home/rongcloud/sealtalk-server/src/db.coffee, reserved word "yield" on line 89
    at SyntaxError (native)
    at Lexer.exports.Lexer.Lexer.error (/home/rongcloud/sealtalk-server/node_modules/coffee-script/lib/coffee-script/lexer.js:682:13)
    at Lexer.exports.Lexer.Lexer.identifierToken (/home/rongcloud/sealtalk-server/node_modules/coffee-script/lib/coffee-script/lexer.js:86:16)
    at Lexer.exports.Lexer.Lexer.tokenize (/home/rongcloud/sealtalk-server/node_modules/coffee-script/lib/coffee-script/lexer.js:33:19)
    at compile (/home/rongcloud/sealtalk-server/node_modules/coffee-script/lib/coffee-script/coffee-script.js:43:32)
    at Object.require.extensions..coffee (/home/rongcloud/sealtalk-server/node_modules/coffee-script/lib/coffee-script/coffee-script.js:19:17)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
```

environment 
```
[rongcloud@test1 sealtalk-server]$ uname -a
Linux test1 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[rongcloud@test1 sealtalk-server]$ node -v
v6.2.2
[rongcloud@test1 sealtalk-server]$ npm -v
3.9.5
[rongcloud@test1 sealtalk-server]$ ./node_modules/coffee-script/bin/coffee -v
CoffeeScript version 1.3.3
```

**Comment by arielyang** [comment]
> 1.9.0 — JANUARY 29, 2015
CoffeeScript now supports ES6 generators. A generator is simply a function that yields.
