### ISSUE TITLE
(node) child_process: options.customFds option is deprecated. Use options.stdio instead. SyntaxError: In D:\wordkspace\sealtalk\sealtalk-server-master\src\db.coffee, reserved word "yield"

### ISSUE THREAD

**Issue by tomatojacky** [sealtalk/sealtalk-server#4]
这个错误怎么解
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
SyntaxError: In D:\wordkspace\sealtalk\sealtalk-server-master\src\db.coffee, reserved word "yield" on line 100
    at SyntaxError (native)
    at Lexer.exports.Lexer.Lexer.error (D:\wordkspace\sealtalk\sealtalk-server-master\node_modules\coffee-script\lib\coffee-s
    at Lexer.exports.Lexer.Lexer.identifierToken (D:\wordkspace\sealtalk\sealtalk-server-master\node_modules\coffee-script\li
    at Lexer.exports.Lexer.Lexer.tokenize (D:\wordkspace\sealtalk\sealtalk-server-master\node_modules\coffee-script\lib\coffe
    at exports.compile.compile (D:\wordkspace\sealtalk\sealtalk-server-master\node_modules\coffee-script\lib\coffee-script\co
    at Object.require.extensions..coffee (D:\wordkspace\sealtalk\sealtalk-server-master\node_modules\coffee-script\lib\coffee
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

**Comment by hf759585780** [comment]
同求

**Comment by arielyang** [comment]
执行什么时候发生的？如果 CoffeeScript 已经升级到最新版本，Node 版本大于 4.0，那么源码更新到最新的源码版本应该能解决这个问题。

**Comment by arielyang** [comment]
是因为本地 node_modules 里的 coffee-script 版本太低。可以尝试 npm install coffee-script 安装最新版本试试

**Comment by tomatojacky** [comment]
CoffeeScript version 1.10.0

**Comment by tomatojacky** [comment]
ok，我晚上试试，这几天又忙别的了

**Comment by tomatojacky** [comment]
npm run initdb
初始化数据的时候就报错了， CoffeeScript version 1.10.0 ， node version is v5.0.0

**Comment by tomatojacky** [comment]
npm run initdb
初始化数据的时候就报错了 ，重装了 coffee-script 的确这个错误就没了

**Comment by tomatojacky** [comment]
▀ ╢░░░░░░░░░░░░░░░░░░░░░
Drop all schemas.
Sync all schemas.
All done!
▀ ╢░░░░░░░░░░░░░░░░░░░░░  数据库初始化执行成功了，谢谢兄台

**Comment by arielyang** [comment]
OK
