### ISSUE TITLE
node install.js出现bug

### ISSUE THREAD

**Issue by slowsay** [sealtalk/sealtalk-server#7]
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: false,
  code: null,
  signal: 'SIGABRT',
  cmd: 'node sync.js --harmony' }

**Comment by slowsay** [comment]
ok,已经解决，conf.js的配置，其实这个应该放在api帮助文档内比较好，在源码区，会让人误解，增加处理时间，不过，你们的产品，也是很棒的，nice!

**Comment by shuise** [comment]
建议收到，列入改进计划，谢谢！

**Comment by FrancisLL** [comment]
conf.js 配置说明在 2.2.0 版本进行改进
